### PR TITLE
Require Chef 12  and update contributing doc

### PR DESCRIPTION
**Pull request by tas50**
Require Chef 12+ (as a runtime dep now)
Replace the old contributing doc
Opscode -> Chef
Add a Github issue template
Add a travis config
Reformat the readme and update installation section
Move dev deps to the Gemfile
Chefstyle autocorrect fixes

### CODE REVIEW

**Comment by stevendanna** [comment]
I'm 👍 on all of the style changes.  Do we actually need to depend on Chef 12 and Ruby 2.2?  This is a very simple plugin that makes some basic API requests.  The users most likely to use it are also those most likely to upgrade slowly.

**Comment by tas50** [comment]
I can back up the dep bumps here since this tool is a bit different from our others. I started out just trying to get the contributing docs updated in all our projects for our migration to DCO. I was running into issues where most of our old-ish projects wouldn't actually pass travis anymore since so many dep gems now require Ruby 2.2+. We've nuked it from just about everything we've pushed lately, plus the 3rd party tools we manage (Foodcritic, Chefspec, Berkshelf). This was just a continuation of that pattern.

**Comment by tas50** [comment]
@stevendanna This work for you now?

**Comment by stevendanna** [comment]
@tas50 Looks good.  I'll try to release it in a bit, want to do some local testing of this first because it has been a while since I've touched this code.

**Pull request merged**
